# Author: Oliver Martin Grooby (16605155)

# Below is a YAML script that will generate the infastracture required
# for the assignment
imports:
# Import the Production Newtwork Jinja Template
- path: production-network-template.jinja
# Import the LAMP Subnetwork Jinja Template 
- path: lamp-subnetwork-template.jinja
# Import the Firewall Jinja Template
- path: firewall-template.jinja
# Import the "Small LAMP VM" Template
- path: small-lamp-vm-template.jinja
# Import the "LAMP VM" Template - which just has an extra core
# and 5GB more disk space because I can
- path: lamp-vm-template.jinja
- path: startup.sh
  name: startup-script

resources:
# The below items create a VPC Network (Production, with 2 Subnets in 2 regions)
# for this assignment
# ************************
# Create Network called production
- name: production
  type: production-network-template.jinja
# Create a subnet in the eu-west4 zone
- name: lamp-net-euw
  type: lamp-subnetwork-template.jinja
  properties:
    ipRange: 10.10.0.0/16
    network: $(ref.production.selfLink)
    region: europe-west4
# Create a subnet in the us-east4 zone
- name: lamp-net-useast
  type: lamp-subnetwork-template.jinja
  properties:
    ipRange: 10.20.0.0/16
    network: $(ref.production.selfLink)
    region: us-east4
# Create a Firewall for the VPC Network, and place Prodcution
# behind it.
- name: lamp
  type: firewall-template.jinja
  properties:
    network: $(ref.production.selfLink)
    protocol: TCP
# Create a "small" (n1-standard-1) VM to run a LAMP
# stack on.
- name: lamp-small
  type: small-lamp-vm-template.jinja
  properties:
    zone: europe-west4-b
    network: $(ref.production.selfLink)
    subnet: $(ref.lamp-net-euw.selfLink)
    tags:
      - http
# Create a "normal" (n1-standard-2) VM to run a LAMP
# stack on. This time on a different subnet and using the 
# alternate template
- name: lamp-normal
  type: lamp-vm-template.jinja
  properties:
    zone: us-east4-b
    network: $(ref.production.selfLink)
    subnet: $(ref.lamp-net-useast.selfLink)
    tags:
      - http