#! /bin/bash
FILE=/configd.txt
if [ -f "$FILE"]; then
    echo "Already configured, skipping!"
else
    MYSQL_ROOT_PASS='password'
    PHPMYADMIN_DIR='phpmyadmin'
    sudo touch /configd.txt
    sudo apt update
    sudo apt -y install apache2 mysql-server php php-mysql libapache2-mod-php php-cli php-mbstring php-gettext
    sudo chmod -R 0755 /var/www/html/
    sudo echo "<?php phpinfo(); ?>" > /var/www/html/index.php 
    sudo systemctl enable apache2
    sudo systemctl start apache2
    sudo phpenmod mcrypt
    sudo phpenmod mbstring
    # The below section is from https://gist.github.com/gggordon/ae4b0a60613e3964b8838b4a630d9b1c
    AUTOGENERATED_PASS=`tr -dc A-Za-z0-9 < /dev/urandom | head -c 64`
    echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
    echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
    echo "phpmyadmin phpmyadmin/mysql/admin-user string root" | debconf-set-selections
    echo "phpmyadmin phpmyadmin/mysql/admin-pass password $MYSQL_ROOT_PASS" | debconf-set-selections
    echo "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASS" |debconf-set-selections
    echo "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASS" | debconf-set-selections
    apt-get --assume-yes install phpmyadmin
    sudo systemctl restart apache2
fi
